export const GET_POKEMON = 'GET_POKEMON'
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR'
export const GET_POKE_LOC = "GET_POKE_LOC"
export const POK_DETAIL = "POK_DETAIL"
export const CLEAR_DETAIL = 'CLEAR_DETAIL'